
quarkus.application.name=bin-available-fileserver

quarkus.banner.enabled=false

# quarkus.log.level=WARN

quarkus.http.port=8080
quarkus.http.root-path=/api

quarkus.otel.logs.enabled=true

quarkus.rest-client.connect-timeout=2000
quarkus.rest-client.read-timeout=2000

node.id=tuxedo-laptop:8081
node.replicas=tuxedo-laptop:8082,tuxedo-laptop:8083
node.main=tuxedo-laptop:8081

client.address=localhost
