
quarkus.application.name=bin-available-fileserver

quarkus.banner.enabled=false

# quarkus.log.level=WARN

quarkus.http.port=8080
quarkus.http.root-path=/api

quarkus.otel.logs.enabled=true

quarkus.rest-client.connect-timeout=2000
quarkus.rest-client.read-timeout=2000

node.id=node-1
node.replicas=node-2,node-3
