
quarkus.application.name=bin-available-fileserver-client

quarkus.banner.enabled=false

quarkus.http.port=9000
quarkus.http.root-path=/api

quarkus.rest-client.connect-timeout=2000
quarkus.rest-client.read-timeout=2000

client.endpoint=admin-gf63thin8rcs:9000
